In [1]:
import pandas as pd

In [4]:
data = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv",sep=";")

In [5]:
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [6]:
from sklearn.model_selection import train_test_split
train , test = train_test_split(data)

In [7]:
train

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.400000,5
1182,10.2,0.400,0.40,2.5,0.068,41.0,54.0,0.99754,3.38,0.86,10.500000,6
1514,6.9,0.840,0.21,4.1,0.074,16.0,65.0,0.99842,3.53,0.72,9.233333,6
923,6.8,0.410,0.31,8.8,0.084,26.0,45.0,0.99824,3.38,0.64,10.100000,6
1532,7.2,0.530,0.13,2.0,0.058,18.0,22.0,0.99573,3.21,0.68,9.900000,6
...,...,...,...,...,...,...,...,...,...,...,...,...
1306,9.7,0.690,0.32,2.5,0.088,22.0,91.0,0.99790,3.29,0.62,10.100000,5
1441,7.4,0.785,0.19,5.2,0.094,19.0,98.0,0.99713,3.16,0.52,9.566667,6
327,10.3,0.440,0.50,4.5,0.107,5.0,13.0,0.99800,3.28,0.83,11.500000,5
352,7.7,0.665,0.00,2.4,0.090,8.0,19.0,0.99740,3.27,0.73,9.300000,5
1405,7.7,0.280,0.30,2.0,0.062,18.0,34.0,0.99520,3.28,0.90,11.300000,7

In [8]:
test

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
611,13.2,0.380,0.55,2.70,0.081,5.0,16.0,1.00060,2.98,0.54,9.4,5
546,7.5,0.550,0.24,2.00,0.078,10.0,28.0,0.99830,3.45,0.78,9.5,6
578,8.8,0.470,0.49,2.90,0.085,17.0,110.0,0.99820,3.29,0.60,9.8,5
1367,6.9,0.540,0.30,2.20,0.088,9.0,105.0,0.99725,3.25,1.18,10.5,6
1159,10.2,0.410,0.43,2.20,0.110,11.0,37.0,0.99728,3.16,0.67,10.8,5
...,...,...,...,...,...,...,...,...,...,...,...,...
763,9.3,0.655,0.26,2.00,0.096,5.0,35.0,0.99738,3.25,0.42,9.6,5
1006,9.1,0.290,0.33,2.05,0.063,13.0,27.0,0.99516,3.26,0.84,11.7,7
205,12.8,0.300,0.74,2.60,0.095,9.0,28.0,0.99940,3.20,0.77,10.8,7
58,7.8,0.590,0.18,2.30,0.076,17.0,54.0,0.99750,3.43,0.59,10.0,5
891,7.2,0.660,0.03,2.30,0.078,16.0,86.0,0.99743,3.53,0.57,9.7,5